<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Batch Deletion' => '批量删除',
    'Article does not exist.' => '文章不存在',
    'Articles' => '文章',
    'Comments' => '评论',
    'Content' => '内容',
    'Cover' => '封面',
    'Create Article' => '创建文章',
    'Created At' => '创建时间',
    'Delete Article' => '删除文章',
    'Description' => '描述',
    'Manage Article' => '管理文章',
    'Published At' => '发表时间',
    'Status' => '状态',
    'Status Active' => '通过',
    'Status Pending' => '待审',
    'Title' => '标题',
    'Update Article' => '更新文章',
    'Updated At' => '更新时间',
    'Views' => '阅读次数',
];
