<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Today, what experience do you need to share?？ Write it down' => '今天，有什么经验需要分享呢？',
    'Write a article' => '立即撰写',
    'Accepted' => '通过',
    'Active' => '通过',
    'Are you sure you want to Accepted this article?' => '你确实要审核通过该文章吗？',
    'Article does not exist.' => '文章不存在',
    'Articles' => '文章',
    'Batch Deletion' => '批量删除',
    'Collect' => '收藏',
    'Collections' => '收藏',
    'Comments' => '评论',
    'Concern' => '关注',
    'Concerned' => '已关注',
    'Concerned will be updated to remind' => '关注后将获得更新提醒',
    'Content' => '内容',
    'Cover' => '封面',
    'Create Article' => '创建文章',
    'Created At' => '创建时间',
    'Delete Article' => '删除文章',
    'Description' => '描述',
    'Hot Topic' => '热门话题',
    'Hot list' => '热门文章',
    'Is Best' => '是否精华',
    'Is Hot' => '是否热门',
    'Is Top' => '是否置顶',
    'Loading...' => '加载中...',
    'Manage Article' => '管理文章',
    'More' => '更多',
    'No introduction' => '暂无介绍',
    'Pending' => '待审',
    'Published At' => '发表时间',
    'Published in' => '发表于',
    'Status' => '状态',
    'Status Active' => '通过',
    'Status Pending' => '待审',
    'Support' => '推荐',
    'Supports' => '推荐',
    'Title' => '标题',
    'Update Article' => '更新文章',
    'Updated At' => '更新时间',
    'Views' => '阅读',
    'collected' => '已收藏',
    '{n, plural, =0{No article} =1{One article} other{# articles}}' => '{n, plural, =0{暂无文章} =1{1 篇文章} other{# 篇文章}}',
    '{n, plural, =0{No comment} =1{One comment} other{# reviews}}' => '{n, plural, =0{暂无评论} =1{1 条评论} other{# 条评论}}',
];
